name: Update README2

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    permissions: # <-- AÑADIDO: Otorga permisos de escritura al token
      contents: write # ¡Esta linea es crucial!
    runs-on: ubuntu-latest
    name: Update Profile README
    
    steps:
      - uses: actions/checkout@4
       with: # <-- AÑADIDO: Asegura la descarga completa del repo
       fetch-depth: 0
      
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
